# Generated by Django 4.1.6 on 2023-02-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_date', models.DateField()),
                ('ccv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCheese',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cheese', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCrust',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crust', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSauce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sauce', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pepperoni', models.BooleanField(default=False)),
                ('chicken', models.BooleanField(default=False)),
                ('ham', models.BooleanField(default=False)),
                ('pineapple', models.BooleanField(default=False)),
                ('peppers', models.BooleanField(default=False)),
                ('mushrooms', models.BooleanField(default=False)),
                ('onions', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzafast.pizzacheese')),
                ('crust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzafast.pizzacrust')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzafast.pizzasauce')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzafast.pizzasize')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzafast.pizzatopping')),
            ],
        ),
    ]
