# Generated by Django 4.1.6 on 2023-02-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzafast', '0002_remove_pizza_topping_pizza_chicken_pizza_ham_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzacheese',
            name='cheese',
            field=models.CharField(max_length=20),
        ),
    ]
