# Generated by Django 4.1.6 on 2023-02-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzafast', '0003_alter_pizzacheese_cheese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='expiry_date',
            field=models.CharField(max_length=5),
        ),
    ]
